import json

def lambda_handler(event, context):
    """
    Adds the user's groups to the 'cognito:groups' claim in the ID token.
    This is triggered before the token is generated by Cognito.
    """
    
    # The group configuration is passed in the event request
    group_config = event.get('request', {}).get('groupConfiguration', {})
    groups_to_override = group_config.get('groupsToOverride', [])

    # If the user is a member of any groups, add them to the token
    if groups_to_override:
        event['response'] = {
            'claimsOverrideDetails': {
                'claimsToAddOrOverride': {
                    'cognito:groups': json.dumps(groups_to_override)
                }
            }
        }
    
    # Return the modified event to Cognito
    return event