# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "aws" {
  region                   = "ca-central-1"
  profile                  = "dev"
  shared_config_files      = ["E:/bsup/proj155-BTAP/AWS/Terraform/T2-ECS-TGW/.aws/config"]
  shared_credentials_files = ["E:/bsup/proj155-BTAP/AWS/Terraform/T2-ECS-TGW/.aws/credentials"]
}
